spring:
  cloud:
    config:
      discovery: 
        enabled: true
        serviceId: config-server
  user:
    roles: ACTUATOR
eureka:
  instance:
    instanceId: ${VHOSTNAME:${HOSTNAME:localhost.shinigami.io}}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    statusPageUrlPath: ${server.context-path}${management.context-path}/info
    healthCheckUrlPath: ${server.context-path}${management.context-path}/health
    leaseRenewalIntervalInSeconds: 5
  client:
    region: default
    serviceUrl:
      defaultZone: http://${VEUREKAUSER:config}:${VEUREKAPASS:config}@${VEUREKAHOST:localhost.shinigami.io}:${VEUREKAPORT:8761}/registry/eureka
    enabled: true
